//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PE.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string angle {
            get {
                return ResourceManager.GetString("angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing radius.
        /// </summary>
        internal static string bearing_radius {
            get {
                return ResourceManager.GetString("bearing_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing radius must not be 0.
        /// </summary>
        internal static string bearing_radius_0 {
            get {
                return ResourceManager.GetString("bearing_radius_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing radius must have a value when calculating offsets.
        /// </summary>
        internal static string bearing_radius_required_for_offset {
            get {
                return ResourceManager.GetString("bearing_radius_required_for_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please calculate first then export.
        /// </summary>
        internal static string calculate_before_export {
            get {
                return ResourceManager.GetString("calculate_before_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate offset curves.
        /// </summary>
        internal static string calculate_offsets {
            get {
                return ResourceManager.GetString("calculate_offsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating 0%.
        /// </summary>
        internal static string calculating_0 {
            get {
                return ResourceManager.GetString("calculating_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating {0}%.
        /// </summary>
        internal static string calculating_percent {
            get {
                return ResourceManager.GetString("calculating_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        internal static string clockwise {
            get {
                return ResourceManager.GetString("clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Velocity.
        /// </summary>
        internal static string ConstantVelocity {
            get {
                return ResourceManager.GetString("ConstantVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter clockwise.
        /// </summary>
        internal static string counter_clockwise {
            get {
                return ResourceManager.GetString("counter_clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycloidal.
        /// </summary>
        internal static string Cycloidal {
            get {
                return ResourceManager.GetString("Cycloidal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Angle [°].
        /// </summary>
        internal static string end_angle {
            get {
                return ResourceManager.GetString("end_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAngle must not be equal to StartAngle.
        /// </summary>
        internal static string end_angle_not_equal_start_angle {
            get {
                return ResourceManager.GetString("end_angle_not_equal_start_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Height [mm].
        /// </summary>
        internal static string end_height {
            get {
                return ResourceManager.GetString("end_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all values.
        /// </summary>
        internal static string enter_all_values {
            get {
                return ResourceManager.GetString("enter_all_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one segment.
        /// </summary>
        internal static string enter_at_least_one_segment {
            get {
                return ResourceManager.GetString("enter_at_least_one_segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Bearing radius.
        /// </summary>
        internal static string enter_bearing_radius {
            get {
                return ResourceManager.GetString("enter_bearing_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number for Bearing radius.
        /// </summary>
        internal static string enter_number_for_bearing_radius {
            get {
                return ResourceManager.GetString("enter_number_for_bearing_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number for OffsetZ.
        /// </summary>
        internal static string enter_number_for_offset_z {
            get {
                return ResourceManager.GetString("enter_number_for_offset_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number for Radius.
        /// </summary>
        internal static string enter_number_for_radius {
            get {
                return ResourceManager.GetString("enter_number_for_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Radius.
        /// </summary>
        internal static string enter_radius {
            get {
                return ResourceManager.GetString("enter_radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel is not properly installed.
        /// </summary>
        internal static string excel_not_installed {
            get {
                return ResourceManager.GetString("excel_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting 0%.
        /// </summary>
        internal static string exporting_0 {
            get {
                return ResourceManager.GetString("exporting_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}%.
        /// </summary>
        internal static string exporting_percent {
            get {
                return ResourceManager.GetString("exporting_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string formula {
            get {
                return ResourceManager.GetString("formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file contains incorrect value(s).
        /// </summary>
        internal static string incorrect_values_in_import_file {
            get {
                return ResourceManager.GetString("incorrect_values_in_import_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [mm].
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be double.
        /// </summary>
        internal static string must_be_double {
            get {
                return ResourceManager.GetString("must_be_double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New layout.
        /// </summary>
        internal static string new_layout {
            get {
                return ResourceManager.GetString("new_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported formula.
        /// </summary>
        internal static string not_supported_formula {
            get {
                return ResourceManager.GetString("not_supported_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset curves.
        /// </summary>
        internal static string offset_curves {
            get {
                return ResourceManager.GetString("offset_curves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move curves Z.
        /// </summary>
        internal static string offset_z {
            get {
                return ResourceManager.GetString("offset_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open layout.
        /// </summary>
        internal static string open_layout {
            get {
                return ResourceManager.GetString("open_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string precision {
            get {
                return ResourceManager.GetString("precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string radius {
            get {
                return ResourceManager.GetString("radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to {0}?.
        /// </summary>
        internal static string save_changes_to_file {
            get {
                return ResourceManager.GetString("save_changes_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout.
        /// </summary>
        internal static string save_layout {
            get {
                return ResourceManager.GetString("save_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segments.
        /// </summary>
        internal static string segments {
            get {
                return ResourceManager.GetString("segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select formula.
        /// </summary>
        internal static string select_formula {
            get {
                return ResourceManager.GetString("select_formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Angle [°].
        /// </summary>
        internal static string start_angle {
            get {
                return ResourceManager.GetString("start_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Height [mm].
        /// </summary>
        internal static string start_height {
            get {
                return ResourceManager.GetString("start_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
    }
}
